### ISSUE TITLE
Shared boards

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir.github.io#2]
The possibilities of sharing a board

**Comment by liar666** [comment]
Hi,

Thanks again for the app! I'm backing up this issue too, because it would save a lot of bandwith to my students (& to save the planet :) ) if I could share them a url with a given blackboard instead of having to share my screen in a videoconferencing tool. The top would be that students could collaborate on a diagram (a-la etherpad)!

**Comment by francoisschwarzentruber** [comment]
Now, it is possible to share boards. But magnets and texts are not shared yet! Work in progress! :)

**Comment by francoisschwarzentruber** [comment]
Boards can now be shared, magnets too. That is not perfect yet. But this issue is too general to remain open. I close it.
