### ISSUE TITLE
Visual indicator of the middle of the screen

### ISSUE THREAD

**Issue by Kerl13** [tableaunoir/tableaunoir.github.io#7]
Hi, first of all great project!
I particularly appreciate that the "next" button only moves to the right by one half-screen so that I and the student can still see the previous half-board when I start writing on the next one.
But it would be even more convenient with a visual indicator of the middle of the board, so that I don't cross the middle of the board when writing on the left half.
Do you think it would be possible (and desirable) to add such a thing? Maybe a discrete thin gray line?

**Comment by francoisschwarzentruber** [comment]
Dear Kerl13,

thank you for your message! Exactly, I actually sometimes divide the screen into two parts. In order to get a visual indicator, press "d" to "divide the screen". It will draw a vertical white line in the middle of the screen to divide the screen.

Your suggestion is interesting. I am not sure but I think that:
1) Such kind of vertical line should be always there. It happens that I need the full blackboard.
2) If that vertical line should appear, it should be very visible hence the white line.

Do not hesitate to comment!

**Comment by Kerl13** [comment]
Oh I see, I didn't figure out you already had thought about that. It looks good to me as it is now then, I agree that it should not always be present :+1:

But there is a bug with electron v10.1.5 then: nothing happens when I press `d`.

**Comment by francoisschwarzentruber** [comment]
Thank you for reporting that bug. I will see what I can do. 
PS: with electron v9.0.0, it works.

**Comment by Kerl13** [comment]
Works with electron v10 as well now, thanks!

**Comment by francoisschwarzentruber** [comment]
Excellent!
